<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/12/28
 * Time: 9:52
 */

namespace restful\controllers;

use common\helpers\MT4;
use common\models\User;
use Yii;
use yii\base\Exception;


class Mt4ServerController extends Base
{

    public function init()
    {
        $request = Yii::$app->request;

        $language = $request->getHeaders()->get('CLIENT-LANG') ? : 'en-US';
        $keys = ['zh-CN', 'zh-TW', 'pl-PL', 'pt-PT','en-US'];

        if(!in_array($language,$keys))
            $language = 'en-US';

        Yii::$app->language = $language;
    }

    /**
     * 复写校验规则，添加白名单
     * @return array
     */
    protected function exceptionalAuthenticationActions()
    {
        //return ['test', 'clients-add-user'];
        return parent::exceptionalAuthenticationActions(); // TODO: Change the autogenerated stub
    }

    public function actionTest() {
        /** @var User $user */
        $user = \Yii::$app->user->getIdentity();
        
        try {
//            $ret = MT4::updateUserInfo($user->mid, [], 'demo');
//            var_dump('updateUserInfo');
//            var_dump($ret);

//            $ret = MT4::getOpenOrder($user->mid, 'demo');
//            var_dump('getOpenOrder');
//            var_dump($ret);

            $ret = MT4::getClosedOrder($user->mid, time()-38400, time(), 'demo');
            var_dump('getClosedOrder');
            var_dump($ret);
        } catch (Exception $e) {
            $e->getCode();
        }
        

    }

    
    /**
     * 在mt4服务器注册账户, 正式 'live'，模拟 'demo'，
     */
    public function actionClientsAddUser() {
        $return = ['result' => true];

        /** @var User $user */
        $user = \Yii::$app->user->getIdentity();
        
        $ret_demo = MT4::registerAccount($user->mid, 'demo');
        if ($ret_demo['e'] !== 0 ) {
            $return['result'] = false;
            $return['message'] = 'fail';
            echo json_encode($return);
        }

        
        $user->mt4_demo_id = $ret_demo['data']['login'];
        $user->mt4_demo_group = $ret_demo['data']['group'];
        $user->save(false);
        
        $return['data']['mt4_demo_id'] = $user->mt4_demo_id;
        echo json_encode($return);
    }
    
    
    public function actionGetDeal() {
        
    }
}