<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/12/7
 * Time: 9:52
 */

namespace restful\controllers;

use Yii;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\auth\QueryParamAuth;
use yii\web\Response;

class TestController extends Base {

    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['contentNegotiator']['formats']['text/html'] = Response::FORMAT_HTML;
        $behaviors['authenticator'] = [
            'class' => CompositeAuth::className(),
            'authMethods' => [
                //HttpBasicAuth::className(),
                //HttpBearerAuth::className(),
                //QueryParamAuth::className(),
            ],
            'except' => $this->exceptionalAuthenticationActions(),
        ];
        return $behaviors;
    }

    /**
     * 复写校验规则，添加白名单
     * @return array
     */
    protected function exceptionalAuthenticationActions()
    {
        return ['test'];
        //return parent::exceptionalAuthenticationActions(); // TODO: Change the autogenerated stub
    }

    public function actionTest(){

        return '1';

    }


    public function actionMg()
    {
        //获取全部的集合名
        $collection = \Yii::$app->mongodb->listCollection();

        //获取在使用的集合名
        $cont = Yii::$app->db;
        $rels = $cont->createCommand("SELECT name FROM {{%instruments}}")->queryAll();
        if (empty($rels)) {
            return ['data' => "基本数据调用失败"];
        }

        $total = array();
        foreach ($rels as $val) {
            $total[] = $val['name'];
        }
        array_push($total, 'system.indexes');  //系统函数进行保留

        foreach ($collection as $v) {
            $status = in_array($v['name'], $total);
            if ($status) {
                $table = $v['name'];
                if ($table == 'system.indexes') {
                    continue;
                } //跳过系统文件

                $collection = \Yii::$app->mongodb->getCollection($table);
                $go_time = time() - 3600 * 24 * 30;     //数据保留30天
                $query = array("time" => array('$lt' => "$go_time"));
                $asd = $collection->remove($query);
                echo '清除 ' . $table . "过期数据 $asd 个 \n";

            } else {
                //删除错误无效的集合
                $aa = \Yii::$app->mongodb->dropCollection($v['name']); //删除无效集合
                echo '清除 ' . $v['name'] . " 无效集合 \n";
            }

        }


    }
} 